apiVersion: batch/v1
kind: Job
metadata:
  name: doscontenedores
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: contenedoruno
        image: python:3.6-alpine
      - name: contenedordos
        image: python:3.6-alpine


